name: build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-lint-linux:
    name: Linux - ompd - build and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Install dbus
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libdbus-1-dev dbus
      - name: Build
        run: cargo build --verbose
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Check format
        run: cargo fmt -- --check

  build-lint-windows:
    name: Windows - ompd - build and lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Build
        run: cargo build --verbose
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Check format
        run: cargo fmt -- --check
