name: Build Linux (x86_64)
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-lint-format:
    uses: ./.github/workflows/linux-build.yml@main
    with:
      upload_artifacts: false
