name: Build Mac (aarch64)
on:
  workflow_call:
    inputs:
      upload_artifacts:
        required: true
        type: boolean
      version:
        required: false
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Check format
        run: cargo fmt -- --check

      - name: Build (dbg)
        run: cargo build --verbose

      - name: Lint
        run: cargo clippy -- -D warnings

      - name: Build (release)
        if: ${{ inputs.upload_artifacts }}
        run: cargo build --verbose --release

      - name: Archive binary
        if: ${{ inputs.upload_artifacts }}
        run: |
          ARCHIVE_FILE=ompd-${{ inputs.version }}-mac-aarch64.tar.gz
          tar czvf $ARCHIVE_FILE -C target/release ompd
          shasum -a 256 $ARCHIVE_FILE > $ARCHIVE_FILE.sha256

      - name: Upload binary
        if: ${{ inputs.upload_artifacts }}
        uses: actions/upload-artifact@v4
        with:
          name: mac-binaries
          path: |
            *.tar.gz
            *.sha256
