name: Build Mac (x86_64)
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  run:
    uses: ./.github/workflows/mac-build.yml
    with:
      upload_artifacts: false
