name: "[ompd] Release"

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUSTUP_MAX_RETRIES: 10

jobs:
  mac:
    uses: ./.github/workflows/mac-build.yml
    with:
      upload_artifacts: true
      version: ${{ github.ref_name }}

  linux:
    uses: ./.github/workflows/linux-build.yml
    with:
      upload_artifacts: true
      version: ${{ github.ref_name }}

  windows:
    uses: ./.github/workflows/windows-build.yml
    with:
      upload_artifacts: true
      version: ${{ github.ref_name }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - mac
      - linux
      - windows
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: binaries
          pattern: "*-binaries"
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: binaries/*
