name: Build Windows (x86_64)
on:
  workflow_call:
    inputs:
      upload_artifacts:
        required: true
        type: boolean

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - name: Build (dbg)
        run: cargo build --verbose
      - name: Check format
        run: cargo fmt -- --check
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Build (release)
        if: ${{ inputs.upload_artifacts }}
        run: cargo build --verbose --release
      - name: Archive binary
        if: ${{ inputs.upload_artifacts }}
        shell: bash
        run: |
          ARCHIVE_FILE=ompd-windows-x86_64.zip
          7z a $ARCHIVE_FILE ./target/x86_64-pc-windows-msvc/release/ompd.exe
          sha256sum $ARCHIVE_FILE > $ARCHIVE_FILE.sha256
      - name: Upload binary
        if: ${{ inputs.upload_artifacts }}
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            *.zip
            *.sha256
